[package]
authors = ["Kirill Bobyrev <kbobyrev.opensource@gmail.com>"]
build = "src/build.rs"
categories = [
  "command-line-interface",
]
description = "Chess engine"
documentation = "https://docs.rs/pabi"
edition = "2021"
homepage = "https://github.com/kirillbobyrev/pabi"
keywords = ["chess", "engine", "machine-learning"]
license = "Apache-2.0"
name = "pabi"
readme = "README.md"
repository = "https://github.com/kirillbobyrev/pabi"
rust-version = "1.78"
version = "0.0.1"
# Reduce the package size by only including things necessary for building it.
include = [
  "/src/**/*.rs",
  "/Cargo.toml",
  "/Cargo.lock",
  "/data/positions.fen",
  "LICENSE",
  "README.md",
]

[dependencies]
arrayvec = "0.7.2"
# TODO: Get rid of error handling? Just panic on errors for performance?
anyhow = "1.0.83"
bitflags = "2.2.1"
itertools = "0.13.0"
sysinfo = "0.30.12"

[dev-dependencies]
criterion = {version = "0.5.1", features = ["html_reports", "cargo_bench_support", "csv_output"]}
iai = "0.1.1"
pretty_assertions = "1.1.0"
shakmaty = "0.27.0"

[[bench]]
harness = false
name = "cycles"

[[bench]]
harness = false
name = "time"

# This is not the most perofrmmance-optimized profile. Use `fast` instead. Read
# BUILDING.md for more information.
[profile.release]
panic = "abort"
# Needed for cargo flamegraph.
debug = true

# TODO: Mention this in BUILDING.md.
# TODO: Test this out once the benchmarks are available and tweak specific
# values. So far, this gives around -8% on parsing FEN/EPD positions.
[profile.fast]
debug = false
codegen-units = 1
inherits = "release"
lto = "fat"
strip = true
# TODO: Oh-oh, this is dangerous! Maybe measure if it gives any benefits.
# overflow-checks = false
# TODO: Tweak inline-threshold.
# TODO: Set profile-generate and profile-use (https://github.com/kirillbobyrev/pabi/issues/9).
