[package]
authors = ["Kirill Bobyrev <kbobyrev.opensource@gmail.com>"]
categories = [
  "command-line-interface",
]
description = "Chess engine"
documentation = "https://docs.rs/pabi"
edition = "2021"
homepage = "https://github.com/kirillbobyrev/pabi"
keywords = ["chess"]
license = "Apache-2.0"
name = "pabi"
readme = "README.md"
repository = "https://github.com/kirillbobyrev/pabi"
version = "0.0.0"
# Reduce the package size by only including things necessary for building it.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/Cargo.lock",
    "LICENSE",
    "README.md",
]


[dependencies]
clap = {version = "3.0.0-rc.9", features = ["derive", "wrap_help"]}
itertools = "0.10"
rustyline = "9.0"
sysinfo = "0.22"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
criterion = "0.3"
iai = "0.1"
proptest = "1.0"

[[bench]]
harness = false
name = "perft"
