[package]
authors = ["Kirill Bobyrev <kbobyrev.opensource@gmail.com>"]
build = "src/build.rs"
categories = [
  "command-line-interface",
]
description = "Chess engine"
documentation = "https://docs.rs/pabi"
edition = "2021"
homepage = "https://github.com/kirillbobyrev/pabi"
keywords = ["chess", "engine", "machine-learning"]
license = "Apache-2.0"
name = "pabi"
readme = "README.md"
repository = "https://github.com/kirillbobyrev/pabi"
rust-version = "1.58.1"
version = "0.0.0"
# Reduce the package size by only including things necessary for building it.
include = [
  "/src/**/*.rs",
  "/Cargo.toml",
  "/Cargo.lock",
  "/data/positions.fen",
  "LICENSE",
  "README.md",
]

[dependencies]
arrayvec = "0.7.2"
# TODO: Get rid of error handling? Just panic on errors for performance?
anyhow = "1.0.54"
bitflags = "1.3.2"
itertools = "0.10.3"
# TODO: Get rid of strum - it can be replaced by 20-30 LOC.
strum = {version = "0.23.0", features = ["derive"]}
sysinfo = "0.23.2"

[dev-dependencies]
criterion = {version = "0.3.5", features = ["html_reports", "cargo_bench_support", "csv_output"]}
iai = "0.1.1"
pretty_assertions = "1.1.0"
shakmaty = "0.20.7"

[build-dependencies]
clap = {version = "3.1.0", features = ["cargo"]}

[[bench]]
harness = false
name = "cycles"

[[bench]]
harness = false
name = "time"

# This is not the most perofrmmance-optimized profile. Use `fast` instead. Read
# BUILDING.md for more information.
[profile.release]
panic = "abort"
# Needed for cargo flamegraph.
debug = true

# TODO: Mention this in BUILDING.md.
# TODO: Test this out once the benchmarks are available and tweak specific
# values. So far, this gives around -8% on parsing FEN/EPD positions.
[profile.fast]
debug = false
codegen-units = 1
inherits = "release"
lto = "fat"
# TODO: Reduce binary size (requires nightly now, should be released in the
# next stable version): https://github.com/rust-lang/cargo/pull/10088
# strip = true
# TODO: Oh-oh, this is dangerous! So far, it doesn't give any benefits for
# parsing positions but might be useful in the future.
# overflow-checks = false
# TODO: Tweak inline-threshold.
# TODO: Set profile-generate and profile-use (https://github.com/kirillbobyrev/pabi/issues/9).
