[package]
authors = ["Kirill Bobyrev <kbobyrev.opensource@gmail.com>"]
build = "src/build.rs"
categories = [
  "command-line-interface",
]
description = "Chess engine"
documentation = "https://docs.rs/pabi"
edition = "2021"
homepage = "https://github.com/kirillbobyrev/pabi"
keywords = ["chess", "engine", "machine-learning"]
license = "Apache-2.0"
name = "pabi"
readme = "README.md"
repository = "https://github.com/kirillbobyrev/pabi"
rust-version = "1.58.1"
version = "0.0.0"
# Reduce the package size by only including things necessary for building it.
include = [
  "/src/**/*.rs",
  "/Cargo.toml",
  "/Cargo.lock",
  "/data/books/*.epd.zip",
  "LICENSE",
  "README.md",
]

[dependencies]
anyhow = "1.0.53"
bitflags = "1.3.2"
clap = {version = "3.0.14", features = ["derive", "wrap_help"]}
itertools = "0.10.3"
rustyline = "9.1.2"
strum = {version = "0.23.0", features = ["derive"]}
sysinfo = "0.23"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[dependencies.zip]
default_features = false
features = ["deflate"]
version = "0.5.13"

[dev-dependencies]
criterion = {version = "0.3.5", features = ["html_reports", "cargo_bench_support", "csv_output"]}
iai = "0.1.1"
pretty_assertions = "1.1.0"

[build-dependencies]
clap = {version = "3.0.14", features = ["cargo"]}

[[bench]]
harness = false
name = "position_parsing"

[profile.release]
# TODO: Reduce binary size (requires nightly now, should be released in the
# next stable version): https://github.com/rust-lang/cargo/pull/10088
# strip = true

# TODO: Mention this in BUILDING.md.
# TODO: Test this out once the benchmarks are available and tweak specific
# values. So far, this gives around -8% on parsing FEN/EPD positions.
[profile.fast]
codegen-units = 1
inherits = "release"
lto = "fat"
# TODO: Oh-oh, this is dangerous! So far, it doesn't give any benefits for
# parsing positions but might be useful in the future.
# overflow-checks = false
# TODO: This should be a rustc flag. So far, parse_position benchmarks actually
# show a regression in performance with this flag turned on. I'm not sure why
# that is, probably better to wait for more benchmarks.
# target-cpu = "native"
# TODO: Tweak inline-threshold.
# TODO: Set profile-generate and profile-use (https://github.com/kirillbobyrev/pabi/issues/9).
