name: Bug
description: Report an issue that would help to improve this project.
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the problem.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add any screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
    