name: Bug report
description: Report a problem or crash in Pabi.
title: "[Bug]: "
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run Pabi...
        2. Enter command...
        3. See the error...
    validations:
     required: false
  - type: textarea
    attributes:
      label: Logs
      description: Paste the logs with `RUST_BACKTRACE=1` and `RUST_LOG=info`.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Operating Systtem
      description: What Operating System are you using?
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: false
