[package]
name = "pabi-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.6", features = ["derive"] }
flate2 = "1.0.30"
pabi = { path = ".." }
tar = "0.4.41"
