[package]
name = "pabi-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
pabi = { path = ".." }
tar = "0.4.40"
flate2 = "1.0.30"
byteorder = "1.5.0"
bincode = "1.3.3"
