[package]
name = "pabi-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bincode = "1.3.3"
byteorder = "1.5.0"
clap = { version = "4.5.4", features = ["derive"] }
flate2 = "1.0.30"
pabi = { path = ".." }
rayon = "1.10"
tar = "0.4.40"
