name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable, "1.80.0"]
        experimental: [false]
        include:
          - os: ubuntu-latest
            toolchain: nightly
            experimental: true
          - os: windows-latest
            toolchain: stable
            experimental: true
          - os: windows-latest
            toolchain: nightly
            experimental: true
          - os: macos-latest
            toolchain: stable
            experimental: true
          - os: macos-latest
            toolchain: nightly
            experimental: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install ${{ matrix.toolchain }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: just build
