name: Build developer documentation
on:
  push:
    branches:
    - main
jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    # Ensure there are no conflicting pushes to GitHub Pages.
    concurrency:
      group: docs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build the docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          # This is developer documentation: include crate-local symbols but
          # don't build documentation for dependencies since it's unlikely to
          # be useful.
          args: --document-private-items --no-deps
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc/
          destination_dir: docs
          force_orphan: true
