name: Build docs
on:
  push:
    branches:
    - main
jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    # Ensure there are no conflicting pushes to GitHub Pages.
    concurrency:
      group: docs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build the docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features --document-private-items --no-deps
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
